<?php
/**
 * Terms & Condition template
 * php version 7.4
 *
 * @category MTAV
 * @package  MTAV
 * @author   Cemtrexlabs <hello@cemtrexlabs.com>
 * @license  https://cemtrexlabs.com 1.0
 * @link     MTAV
 */

$privacy_page_link = get_permalink(get_page_by_path('Privacy Policy'));
?>

<div class="container">
    <h5>MORETHANAVOTE.ORG TERMS OF USE</h5>
    <p>Effective Date: June 17, 2020</p>
    <p>Welcome to More Than A Vote’s website, www.morethanavote.org. This website and its subdomains are owned and operated by MORE THAN A VOTE, INC (“MTAV,” “we,” “our,” and “us”). Except as otherwise noted herein, these terms of use (the “Terms of Use”) govern your use of The More Than A Vote Organization website and any other online or mobile website applications or digital services operated by MTAV and/or its affiliates that post a link to these Terms of Use (collectively, the “Site”). Please read these Terms of Use carefully – they form a contract between you and MTAV. By accessing or viewing the Site or participating in or using any service offered on this Site (collectively, the “Services”), you agree to these Terms of Use. If you do not agree to these Terms of Use, you should not access or use the Site. MTAV reserves the right to make changes to the Site and to these Terms of Use from time to time. The amended Terms of Use will automatically be effective when posted on this Site. For this reason, MTAV encourages you to review these Terms of Use whenever you use our Site because by visiting the Site, you agree to accept any such changes. MTAV provides you with access to and use of the Site subject to your compliance with these Terms of Use.</p>
    <p>All references to “you” or “your,” as applicable, mean the person that registers for, accesses, or uses the Services. You represent and warrant that you are at least 16 years of age, or if you are ages 13 to 16 years of age, that you are visiting the Site under the supervision of a parent or guardian who has agreed to these Terms. If you are under 16 years of age, your parent or guardian must provide written consent for you to use the Site. Our Site is not intended for those under the age of 13.</p>
    <div class="spacer"></div>
    <h5>use of the site</h5>
    <p>When you access this Site, you agree to comply with these Terms of Use and any other policies or requirements posted on the Site. You agree to abide by all applicable laws, rules, and regulations when registering for, accessing, or using the Services, and may not engage in fraud or misuse of the Services or any conduct that is harmful or harassing to anybody.</p>
    <p>Violating the security of the Services is prohibited and may result in criminal and/or civil liability. We may investigate incidents involving such violations and may involve, and will cooperate with, law enforcement if a criminal violation is suspected. Examples of security violations include, without limitation, unauthorized access to or use of data or systems including any attempt to probe, scan, or test the vulnerability of the Services or to breach security or authentication measures, unauthorized monitoring of data or traffic, interference with service to any user, host, or network including, without limitation, mail bombing, news bombing, other flooding techniques, deliberate attempts to overload a system, forging any TCP-IP packet header, e-mail header, or any part of a message header, except for the authorized use of aliases or anonymous remailers, and using manual or electronic means to avoid any use limitations. Without limiting the foregoing, you must not do (and agree not to do) any of the following:</p>
    <ol class="one-tab">
        <li>Violate any applicable law or legal requirement.</li>
        <li>Engage in fraud or misuse of the Services.</li>
        <li>Engage in conduct that is harmful or harassing to anybody.</li>
        <li>Post, upload, publish, submit, or transmit any content that:</li>
            <ul class="one-tab">
                <li>Infringes, misappropriates, or violates a third-party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy;</li>
                <li>Violates, or encourages any conduct that would violate, any applicable law or ive rise to civil or criminal liability;</li>
                <li>Is fraudulent, false, misleading, or deceptive;</li>
                <li>Is defamatory, obscene, pornographic, vulgar, or offensive;</li>
                <li>Promotes discrimination, bigotry, racism, hatred, harassment, or harm against any individual or group;</li>
                <li>Is violent or threatening or promotes violence or actions that are threatening to any other person;</li>
                <li>Promotes illegal or harmful activities or substances;</li>
                <li>Constitutes spam, or competes with our business;</li>
                <li>Contains any computer virus or other malicious code designed to attack, damage, divert, take over, disable, overburden, or otherwise impair the Services.</li>
            </ul>
        <li>Attempt to scrape or collect any personal or private information from the Services or from other users of the Services.</li>
        <li>Resell the Services, in whole or in part, or any content residing or displayed within or through the Services.</li>
        <li>Intercept, monitor, damage, or modify any communication not intended for you.</li>
        <li>Otherwise impersonate or misrepresent your affiliation with any person or entity.</li>
        <li>Alter the way that an aspect of a Site we provide is displayed or delivered to other users.</li>
        <li>Access, tamper with, or use non-public areas of a Site we provide, our computer systems, or the technical delivery systems of us or our providers.</li>
        <li>Attempt to probe, scan, or test the vulnerability of the Services or breach any security or authentication measures.</li>
        <li>Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, by sending a virus, overloading, flooding, spamming, or mail-bombing the Services.</li>
        <li>Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure intended to protect, limit access to or control the Services.</li>
        <li>Access the Services if we have requested that you refrain from such access.</li>
        <li>Attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Services.</li>
        <li>Assist or permit anybody to violate these Terms of Use.</li>
    </ol>
    <p>We and our third-party partners reserve the right to restrict, block access to, suspend or terminate the Services for any reason or no reason, without notice, at any time.</p>
    <p>You acknowledge that we have no obligation to monitor your access to or use of the Services for violations of the Terms of Use, or to review any content you submit to us. However, we have the right to do so for the purpose of operating and improving the Services (including, without limitation, for fraud prevention, risk assessment, investigation, and customer support purposes), to ensure your compliance with the Terms of Use, and to comply with applicable law or the order or requirement of a court, consent decree, administrative agency, or other governmental body.</p>
    <p>In addition, we reserve the right to change and improve the features and functionality of the Services at any time, which includes adding, modifying, or removing features and functionality of the Services, or updating how our Services are provided.</p>
    <div class="spacer"></div>
    <h5>TRADEMARKS, COPYRIGHTS, AND RESTRICTIONS</h5>
    <p>All material on the Site, including, but not limited to images, artwork, photographs, moving images, characters, names, graphics, logos, files, service marks, computer code, illustrations, audio clips, video clips, user interfaces, visual interfaces, the design, structure, selection, coordination, “look and feel” and arrangement of these items, is protected by copyrights, trademarks, service marks, trade dress, patents, moral rights, or other proprietary rights (“Content”) which are owned and/or controlled by MTAV or its affiliates, or by other parties that have licensed their material to MTAV, and that these rights are valid and protected in all forms, media, and technologies existing now and hereinafter developed. Your use of this Site shall not grant you any claim of ownership over any Content. You may use material from the Site only for your own personal, non-commercial use, provided that you maintain any notices contained in the Content, or maintained by the Licensor or Author, such as all copyright notices, trademark legends, attributions, by-lines, or other proprietary rights notices. Unauthorized modification of the materials or use of the materials for any other purpose is a violation of the Federal copyright and trademark laws and other proprietary rights. Material from the Site may not be copied, reproduced, republished, uploaded, posted, transmitted, sold, rented, leased, displayed, performed, broadcast, or distributed in any way without express authorization. The use of any such material on any other website, including by linking or faming, or in any networked computer environment, unless expressly authorized, is prohibited.</p>
    <p>For permission to use Content from this Site or from marketing material authored by MTAV, you must request written permission in advance and provide full attribution.</p>
    <div class="spacer"></div>
    <h5>copyrights</h5>
    <p>MTAV respects the rights of all copyright holders. If you believe that your work has been copied in a way that constitutes copyright infringement, or that your intellectual property rights have been otherwise violated, please provide MTAV the following information required by the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act, 17 U.S.C. 512:</p>
    <p>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; Identification of the copyright work claimed to have been infringed, or, if multiple copyrighted works at a single online website are covered by a single notification, a representative list of such works at that website; Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material; Information reasonably sufficient to permit us to contact the complaining party; A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
    <p>For copyright inquiries under the Digital Millennium Copyright Act please contact us at:legal@morethanavote.org or deliver the items above to MTAV’s Designated Copyright Agent at:</p>
    <p class="one-tab">Copyright Agent</p>
    <p class="one-tab">More Than A Vote, Inc</p>
    <p class="one-tab">1500 El Centro Ave, 2nd Floor</p>
    <p class="one-tab">Los Angeles, CA 90028</p>
    <p>We will respond quickly to notices of alleged copyright infringement that are duly reported to our Designated Copyright Agent. MTAV will disable and/or remove access to the Site for users who are repeat infringers. While MTAV considers all such notices seriously, you may be liable for damages (including costs and attorneys’ fees) if you materially misrepresent that content or activity is infringing. Accordingly, if you are uncertain whether material infringes your copyrights (including whether use of copyright material may constitute fair use), you may wish to seek the advice of an attorney.</p>
    <div class="spacer"></div>
    <h5>PRIVACY</h5>
    <p>MTAV respects the privacy of the visitors to the Site. To see the Site's Privacy Policy, which explains our practices related to the collection and use of your information through or in connection with the Site or the Services, please <a href="<?php echo esc_url($privacy_page_link);?>">click here</a>. The Privacy Policy is incorporated into these Terms of Use, and you understand that through your use of the Site or the Services, you consent to the collection and use of your personal information.</p>
    <div class="spacer"></div>
    <h5>LINKED SITES</h5>
    <p>The Site may contain links to third party websites on the Internet that take you outside of the Site and the Services ("Linked Sites"). Linked Sites are operated subject to their own terms of use and privacy policies. You should be sure that you read and agree to those policies. MTAV does not control, endorse, sponsor, recommend, or otherwise accept responsibility for the content of such Linked Sites, nor do we make any warranties or representations, express or implied, regarding the content (or the accuracy, currency, or completeness of such content on any Linked Sites. The links to these websites are for your convenience only, and you access them at your own risk. MTAV welcomes links to the Site. You may establish a link to the Site, provided that the link does not state or imply any sponsorship or endorsement of your website by MTAV, its affiliates, or any group or individual affiliated with MTAV. You may not use on your website any logos, trademarks, service marks, or other copyrighted materials appearing on the Site, including but not limited to any logos or characters, without the express written consent of the owner of the mark or right. You may not frame or otherwise incorporate into another website any of the Content or other materials on the Site without prior written consent.</p>
    <p>MTAV welcomes links to the Site. You may establish a link to the Site, provided that the link does not state or imply any sponsorship or endorsement of your website by MTAV, its affiliates, or any group or individual affiliated with MTAV. You may not use on your website any logos, trademarks, service marks, or other copyrighted materials appearing on the Site, including but not limited to any logos or characters, without the express written consent of the owner of the mark or right. You may not frame or otherwise incorporate into another website any of the Content or other materials on the Site without prior written consent.</p>
    <div class="spacer"></div>
    <h5>UNSOLICITED CREATIVE SUBMISSIONS/COMMUNICATIONS</h5>
    <p>MTAV does not accept or consider creative ideas, suggestions or materials other than those MTAV has specifically requested. This is to avoid the possibility of future misunderstandings when projects independently developed by MTAV or its agents might seem to others to be similar to their own creative ideas, suggestions or materials. MTAV's practice is that creative ideas, suggestions or materials are only accepted for consideration when requested by MTAV, and submitted by a franchised literary agent or production executive with whom MTAV has established a working relationship, and from whom MTAV has received an executed submission agreement. MTAV’s policy is to delete or discard any such unsolicited submissions/communications without reading, forwarding or responding to them.</p>
    <div class="spacer"></div>
    <h5>indemnification</h5>
    <p>You agree to defend, indemnify, and hold harmless MTAV, its officers, directors, employees, affiliates and agents from and against any claims, losses, damages, fines, penalties, or other liabilities in any way associated with (i) your use of and access to the Site or Services; (ii) your violation of any of the Terms of Use; and (iii) your violation of any third party right, including any copyright, trademark, trade secret, or privacy right related to your use of the Site.</p>
    <div class="spacer"></div>
    <h5>disclaimer</h5>
    <p>THE INFORMATION AND MATERIALS ON THE SITE ARE PROVIDED “AS IS” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, MTAV DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. MTAV DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE MATERIALS WILL BE WITHOUT INTERRUPTION OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT MTAV OR THE SERVER THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. MTAV DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE INFORMATION OR MATERIALS ON THE SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT MTAV) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. THE INFORMATION AND MATERIAL THAT YOU READ ON THE SITE IS PROVIDED FOR ENTERTAINMENT PURPOSES. THE INFORMATION AND OPINIONS EXPRESSED IN ANY BULLETIN BOARDS, CHAT ROOMS, OR OTHER FORUMS CONDUCTED ON THE SITE (“FORUMS”) ARE NOT NECESSARILY THOSE OF MTAV OR ITS AFFILIATED OR RELATED ENTITIES OR CONTENT PROVIDERS, AND MTAV MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THAT INFORMATION OR THOSE OPINIONS. FURTHERMORE, NEITHER MTAV NOR ITS AFFILIATED OR RELATED ENTITIES OR ITS CONTENT PROVIDERS ARE RESPONSIBLE OR LIABLE TO ANY PERSON OR ENTITY WHATSOEVER (INCLUDING, WITHOUT LIMITATION, PERSONS WHO MAY USE OR RELY ON SUCH DATA/MATERIALS OR TO WHOM SUCH DATA/MATERIALS MAY BE FURNISHED) FOR ANY LOSS, DAMAGE (WHETHER ACTUAL, CONSEQUENTIAL, PUNITIVE, OR OTHERWISE), INJURY, CLAIM, LIABILITY OR OTHER CAUSE OF ANY KIND OR CHARACTER WHATSOEVER BASED UPON OR RESULTING FROM ANY INFORMATION OR OPINIONS PROVIDED IN THE WEB SITE.</p>
    <p>THE INFORMATION AND OPINIONS EXPRESSED IN ANY BULLETIN BOARDS, CHAT ROOMS, OR OTHER FORUMS CONDUCTED ON THE SITE (“FORUMS”) ARE NOT NECESSARILY THOSE OF MTAV OR ITS AFFILIATED OR RELATED ENTITIES OR CONTENT PROVIDERS, AND MTAV MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THAT INFORMATION OR THOSE OPINIONS. FURTHERMORE, NEITHER MTAV NOR ITS AFFILIATED OR RELATED ENTITIES OR ITS CONTENT PROVIDERS ARE RESPONSIBLE OR LIABLE TO ANY PERSON OR ENTITY WHATSOEVER (INCLUDING, WITHOUT LIMITATION, PERSONS WHO MAY USE OR RELY ON SUCH DATA/MATERIALS OR TO WHOM SUCH DATA/MATERIALS MAY BE FURNISHED) FOR ANY LOSS, DAMAGE (WHETHER ACTUAL, CONSEQUENTIAL, PUNITIVE, OR OTHERWISE), INJURY, CLAIM, LIABILITY OR OTHER CAUSE OF ANY KIND OR CHARACTER WHATSOEVER BASED UPON OR RESULTING FROM ANY INFORMATION OR OPINIONS PROVIDED IN THE WEB SITE.</p>
    <div class="spacer"></div>
    <h5>Limitation of liability</h5>
    <p>TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, IN NO EVENT SHALL MTAV, OR ITS PRESENT OR FUTURE PARENTS OR AFFILIATED COMPANIES (OR ITS OFFICERS, DIRECTORS, AGENTS OR EMPLOYEES), BE LIABLE TO YOU FOR ANY PERSONAL INJURY, PROPERTY DAMAGE, LOST PROFITS, LOSS OF REVENUE, COST OF SUBSTITUTE GOODS OR SERVICES, LOSS OF DATA, LOSS OF GOODWILL, BUSINESS INTERRUPTION, WORK STOPPAGE, COMPUTER AND/OR DEVICE OR TECHNOLOGY FAILURE OR MALFUNCTION OR FOR ANY FORM OF DIRECT OR INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF USE, ANY ALLEGED FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, OR DELAY IN SERVICE, OPERATION, OR TRANSMISSION OF THE SITE, OR ANY ALLEGED COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OF PROPERTY, AND/OR UNAUTHORIZED ACCESS TO, ALTERATION OF, OR USE OF OR POSTING OF ANY RECORD, CONTENT, OR TECHNOLOGY, PERTAINING TO OR ON THE SITE. YOU AGREE THAT THIS LIMITATION OF LIABILITY APPLIES WHETHER SUCH ALLEGATIONS ARE BASED ON WARRANTY, CONTRACT, TORT, NEGLIGENCE, OR OTHERWISE, REGARDLESS OF THE BASIS UPON WHICH LIABILITY IS CLAIMED AND EVEN IF MTAV OR ITS PRESENT OR FUTURE PARENTS OR AFFILIATED COMPANIES HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, YOU ALSO SPECIFICALLY ACKNOWLEDGE THAT MTAV AND/OR ITS PRESENT OR FUTURE PARENTS AND AFFILIATED COMPANIES ARE NOT LIABLE FOR ANY ACTUAL OR ALLEGED DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF OTHER USERS OF THE SITE OR ANY OTHER THIRD PARTIES. IN NO EVENT WILL MTAV’s AGGREGATE LIABILITY (OR THE AGGREGATE LIABILITY OF ITS OFFICERS, DIRECTORS, AFFILIATES, AGENTS, AND EMPLOYEES) ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF USE, THE SITE, OR THE SERVICES (WHETHER IN CONTRACT, TORT, NEGLIGENCE, WARRANTY OR OTHERWISE) EXCEED $100. ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE WEBSITE MUST BEGIN WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>
    <p>IF APPLICABLE LAW DOES NOT ALLOW ALL OR ANY PART OF THE ABOVE LIMITATION OF LIABILITY TO APPLY TO YOU, THE LIMITATIONS WILL APPLY TO YOU ONLY TO THE EXTENT PERMITTED BY APPLICABLE LAW.</p>
    <div class="spacer"></div>
    <h5>JURISDICTIONAL ISSUES</h5>
    <p>The Materials and all other content and features on the Site are presented for the purpose of providing entertainment, news and/or information and/or promoting programs, films, music, games, and other products and/or services that are or may become available in the United States, its territories, possessions, and protectorates. Any and all disputes, claims and controversies arising out of or in connection with your access to, and/or use of the Site, and/or the provision of products, content, services, and/or technology on or through the Site shall be governed by and construed exclusively in accordance with the laws and decisions of the State of California applicable to contracts made, entered into and performed entirely therein, without giving effect to its conflict of laws provisions.</p>
    <div class="spacer"></div>
    <h5>DISPUTES/ARBITRATION. PLEASE READ THIS SECTION CAREFULLY - IT MAY SIGNIFICANTLY AFFECT YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT</h5>
    <p>Any dispute relating in any way to these Terms of Use (including the validity or enforceability of these Terms or this arbitration provision), your visit to the Site, the Services, or to any transaction with MTAV shall be submitted to confidential arbitration in Los Angeles, California. However, if you have in any manner violated or threatened to violate any of MTAV’s intellectual property rights, MTAV may seek injunctive or other appropriate relief in any state or federal court in the state of California. You consent to exclusive jurisdiction and venue in these courts. Any arbitration under this agreement and these Terms of Use shall be conducted under the prevailing rules of the American Arbitration Association. The arbitrator's award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, you agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated or representative action.</p>
    <div class="spacer"></div>
    <h5>Contact us</h5>
    <p>If you have questions about these Terms of Use or the Services, you may contact us at <a href="mailto:legal@morethanavote.org">legal@morethanavote.org</a>.</p>
</div>
